### ISSUE TITLE
IndexError when running with `--zsh`

### ISSUE THREAD

**Issue by andreyfedoseev** [CSRedRat/topalias#11]
* topalias version: 2.0.8
* Python version: 3.8.6
* Operating System: Ubuntu 20.10

### What I Did

I ran

```
topalias --zsh
```

```
Traceback (most recent call last):
  File "/home/andrey/.local/bin/topalias", line 8, in <module>
    sys.exit(cli())
  File "/home/andrey/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/andrey/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/andrey/.local/lib/python3.8/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/home/andrey/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andrey/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/andrey/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/andrey/.local/lib/python3.8/site-packages/topalias/cli.py", line 109, in cli
    return ctx.invoke(main)
  File "/home/andrey/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/andrey/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/andrey/.local/lib/python3.8/site-packages/topalias/cli.py", line 127, in main
    ctx.forward(top_history)  # pylint: disable=no-value-for-parameter
  File "/home/andrey/.local/lib/python3.8/site-packages/click/core.py", line 628, in forward
    return self.invoke(cmd, **kwargs)
  File "/home/andrey/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/andrey/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/andrey/.local/lib/python3.8/site-packages/topalias/cli.py", line 150, in top_history
    core.print_history(acronym_minimal_length),
  File "/home/andrey/.local/lib/python3.8/site-packages/topalias/aliascore.py", line 194, in print_history
    command_bank = load_command_bank(filtering=ALIASES_FILTER)
  File "/home/andrey/.local/lib/python3.8/site-packages/topalias/aliascore.py", line 179, in load_command_bank
    clear_line = line.split(";")[1].rstrip()
IndexError: list index out of range
```

**Comment by CSRedRat** [comment]
Can you add your ~/.zsh_history file to reproduce problem?

**Comment by zabuldon** [comment]
That issue was caused by the new lines in the body of history record.
Example of records caused the same:

: 1602769603:0;telnet my_cool_host 22
: 1602769603:0;python3 cli.py -u sergey.isachenko --region eu-west-1 -a user -t user -p 'password' &&\
aws eks update-kubeconfig --name cluster --region eu-west-1 --profile user
: 1602769603:0;ssh -i ~/.ssh/id_rsa -l root my_cool_host


In this example there is \n after &&\ and tool fails on the next line (aws eks update-kubeconfig --name cluster --region eu-west-1 --profile user) as there is no ;, so split doesn't work.

**Comment by CSRedRat** [comment]
Multiline command in history will be supported in next release: https://github.com/CSRedRat/topalias#todo
I will inform about release with this feature.
Thank you @zabuldon for your example.

**Comment by zabuldon** [comment]
In my opinion better to add some "stub" to prevent seeing IndexError while you are working on multiline support.

**Comment by CSRedRat** [comment]
I add "stub" in 2.0.11, please update:
```
pip3 install -U --user topalias
# or
pip3 install -U --user topalias==2.0.11
```

**Comment by morozsm** [comment]
It has been fixed in last pull request. Should be fixed in next release.
