### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Mte90** [CSRedRat/topalias#16]
* topalias version: last
* Python version: 3.8
* Operating System: linux

### Description

```
topalias - linux bash/zsh alias generator & history analytics https://github.com/CSRedRat/topalias
File .bash_aliases not found in any of the directories
File .bash_aliases not found in any of the directories
Traceback (most recent call last):
  File "/usr/local/bin/topalias", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/topalias/cli.py", line 109, in cli
    return ctx.invoke(main)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/topalias/cli.py", line 126, in main
    core.collect_alias()
  File "/usr/local/lib/python3.8/dist-packages/topalias/aliascore.py", line 78, in collect_alias
    with open(find_aliases(), "r", encoding="utf-8") as aliases_data:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/topalias/data/.bash_aliases'
```

### What I Did

```
topalias
```

**Comment by Mte90** [comment]
I don't have that file and I use a custom shell file to store my alias but the command should work also without it, right?

**Comment by CSRedRat** [comment]
Do you have ~/.bash_aliases?
```
ls -la ~/.bash_aliases
```
Try:
```
topalias history
# and
topalias -f /home/user
```
I add more debug info in utility in next release with --debug flag.

**Comment by Mte90** [comment]
No I don't have that file and I tried `topalias -f /home/mte90` but again the error.

**Comment by CSRedRat** [comment]
@Mte90 fixed in version 2.0.12, please update:
```
pip3 install -U --user topalias
# or
pip3 install -U --user topalias==2.0.12
```

**Comment by Mte90** [comment]
Now works :-)
I see that suggest alias that I use to create another alias, maybe can use `alias` command to detect them.

**Comment by morozsm** [comment]
@Mte90 Please close the issue, once confirmed fixed.

Thank you.
